# DNA System Configuration

# Configurazione generale
general:
  name: "TradingDNA 2.0"
  version: "2.0.0"
  description: "Sistema di Trading Algoritmico Biologico"

# Integrazione con altri sistemi biologici
systems:
  immune:
    enabled: true
    config_file: "config/immune.yaml"
    risk_checks: true
    
  metabolism:
    enabled: true
    config_file: "config/metabolism.yaml"
    capital_management: true
    
  nervous:
    enabled: true
    config_file: "config/nervous.yaml"
    realtime_analysis: true
    
  endocrine:
    enabled: true
    config_file: "config/endocrine.yaml"
    parameter_adaptation: true
    
  reproductive:
    enabled: true
    config_file: "config/reproductive.yaml"
    strategy_evolution: true

# Configurazione dati
data:
  # Percorsi base
  base_path: "data/market/"
  
  # Ratio split dataset
  split_ratios:
    training: 0.7
    validation: 0.15
    testing: 0.15
    
  # Validazione dati
  validation:
    check_missing: true
    check_ordering: true
    required_columns:
      - "open"
      - "high"
      - "low"
      - "close"
      - "volume"
  
  # Training dataset
  training:
    pairs:
      - symbol: "BTC/USDT"
        timeframes: ["1h", "4h", "1d"]
        candles: 5000  # Numero di candele per il training
      - symbol: "ETH/USDT"
        timeframes: ["1h", "4h", "1d"]
        candles: 5000
      
  # Testing dataset  
  testing:
    pairs:
      - symbol: "BTC/USDT"
        timeframes: ["1h", "4h", "1d"]
        candles: 1000  # Numero di candele per il testing
      - symbol: "ETH/USDT"
        timeframes: ["1h", "4h", "1d"]
        candles: 1000
      
  # Paper trading dataset
  paper_trading:
    pairs:
      - symbol: "BTC/USDT"
        timeframes: ["1m", "5m", "15m", "1h"]
        candles: 1000  # Numero di candele per paper trading
      - symbol: "ETH/USDT"
        timeframes: ["1m", "5m", "15m", "1h"]
        candles: 1000

# Configurazione strategie
strategies:
  base_path: "strategies/"
  auto_discovery: true
  validation_required: true
  max_active: 5
  
  # Parametri evoluzione
  evolution:
    population_size: 100
    generations: 50
    mutation_rate: 0.1
    crossover_rate: 0.8
    
  # Parametri validazione
  validation:
    min_trades: 100
    min_win_rate: 0.55
    min_profit_factor: 1.5
    max_drawdown: 0.2

# Configurazione indicatori
indicators:
  base_path: "indicators/"
  auto_discovery: true
  cache_enabled: true
  cache_size: 1000
  
  # Pattern Recognition
  pattern_recognition:
    min_pattern_length: 5
    max_pattern_length: 20
    min_confidence: 0.7
    similarity_threshold: 0.8
    correlation_weight: 0.4
    length_weight: 0.2
    quality_threshold: 0.6
    max_patterns: 1000

  # RSI
  rsi:
    period: 14
    overbought: 70
    oversold: 30
    signal_threshold: 0.6
    weight: 1.0

  # MACD
  macd:
    fast_period: 12
    slow_period: 26
    signal_period: 9
    signal_threshold: 0.6
    weight: 1.0

  # Bollinger Bands
  bollinger:
    period: 20
    num_std: 2.0
    signal_threshold: 0.8
    weight: 1.0

  # Volume
  volume:
    vwap_period: 14
    volume_ma_period: 20
    signal_threshold: 0.6
    weight: 1.0

  # Strong Signal
  strong_signal:
    window_size: 5
    trend_threshold: 0.001
    signal_multiplier: 100.0
    weight: 1.0
    
  # Parametri calcolo
  computation:
    parallel: true
    max_workers: 4
    batch_size: 1000

# Configurazione segnali
signals:
  aggregation_method: "weighted"  # weighted, majority, unanimous
  min_confidence: 0.7
  confirmation_required: true
  
  # Filtri
  filters:
    volatility:
      enabled: true
      min_atr: 0.01
      max_atr: 0.05
    volume:
      enabled: true
      min_volume: 1000000
    trend:
      enabled: true
      lookback_periods: 20

# Configurazione backtest
backtest:
  engine: "vectorized"  # vectorized, event_driven
  commission: 0.001  # 0.1%
  slippage: 0.0005  # 0.05%
  
  # Parametri report
  reporting:
    save_trades: true
    plot_equity: true
    metrics:
      - "sharpe_ratio"
      - "sortino_ratio"
      - "max_drawdown"
      - "win_rate"
      - "profit_factor"

# Configurazione ottimizzazione
optimization:
  method: "SLSQP"  # SLSQP per ottimizzazione vincolata
  parallel: true
  max_workers: 4
  
  # Bounds per ottimizzazione parametri
  pattern_recognition:
    min_pattern_length: [3, 10]
    max_pattern_length: [15, 30]
    min_confidence: [0.5, 0.9]
    similarity_threshold: [0.6, 0.95]
    correlation_weight: [0.2, 0.6]
    length_weight: [0.1, 0.4]
    quality_threshold: [0.4, 0.8]

  rsi:
    period: [5, 30]
    overbought: [60, 85]
    oversold: [15, 40]
    signal_threshold: [0.3, 0.9]
    
  macd:
    fast_period: [5, 20]
    slow_period: [15, 40]
    signal_period: [5, 15]
    signal_threshold: [0.3, 0.9]
    
  bollinger:
    period: [10, 30]
    num_std: [1.5, 3.0]
    signal_threshold: [0.3, 0.9]
    
  volume:
    vwap_period: [5, 30]
    volume_ma_period: [10, 40]
    signal_threshold: [0.3, 0.9]

  strong_signal:
    window_size: [3, 10]
    trend_threshold: [0.0005, 0.002]
    signal_multiplier: [50.0, 150.0]
    weight: [0.5, 1.5]

# Configurazione logging
logging:
  level: "INFO"
  file_enabled: true
  console_enabled: true
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
