# Portfolio Configuration

# Gestione capitale
capital:
  initial: 10000  # USDT
  reserve: 0.2    # 20% del capitale tenuto come riserva
  max_per_trade: 0.05  # Max 5% del capitale per trade
  
# Gestione rischio
risk:
  max_daily_drawdown: 0.03  # 3% max drawdown giornaliero
  max_position_risk: 0.01   # 1% rischio per posizione
  max_correlation: 0.7      # Correlazione massima tra posizioni
  position_sizing:
    method: "risk_parity"   # risk_parity, equal_weight, kelly
    volatility_window: 20   # Giorni per calcolo volatilità
    
# Stop loss
stop_loss:
  enabled: true
  type: "adaptive"  # fixed, trailing, adaptive
  initial: 0.02     # 2% iniziale
  trailing: 0.005   # 0.5% trailing
  atr_multiplier: 2.0
  
# Take profit
take_profit:
  enabled: true
  type: "multi_target"  # single, multi_target
  targets:
    - level: 0.01  # 1%
      size: 0.3    # 30% della posizione
    - level: 0.02  # 2%
      size: 0.3    # 30% della posizione
    - level: 0.03  # 3%
      size: 0.4    # 40% della posizione
      
# Gestione posizioni
position:
  max_concurrent: 5
  min_holding_time: 300  # secondi
  max_holding_time: 172800  # 48 ore in secondi
  
# Diversificazione
diversification:
  min_pairs: 2
  max_pairs: 5
  sector_limits:
    defi: 0.3     # Max 30% in DeFi
    layer1: 0.4   # Max 40% in Layer 1
    gaming: 0.2   # Max 20% in Gaming
    
# Rebalancing
rebalancing:
  enabled: true
  frequency: "daily"  # hourly, daily, weekly
  threshold: 0.05    # 5% deviation trigger
  max_slippage: 0.001  # 0.1% max slippage
  
# Performance metrics
metrics:
  tracking:
    - "sharpe_ratio"
    - "sortino_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
  target_sharpe: 1.5
  min_win_rate: 0.55
