# Logging Configuration

# Configurazione globale
global:
  log_level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  encoding: "utf-8"

# Configurazione file di log
file:
  enabled: true
  path: "logs"
  max_size_kb: 400  # Limite massimo di 400KB per file
  max_total_size_mb: 50  # Limite massimo totale directory logs
  backup_count: 5
  compress: true
  retention:
    days: 30  # Mantieni i log per 30 giorni
    auto_clean: true  # Pulizia automatica dei log vecchi
    compress_after_days: 7  # Comprimi i log più vecchi di 7 giorni

# Configurazione console
console:
  enabled: true
  color: true
  detailed: false
  visual: true  # Abilita il visual logging con Rich

# Configurazione visual
visual:
  enabled: true
  colors:
    info: "cyan"
    warning: "yellow"
    error: "red bold"
    critical: "red bold reverse"
    success: "green bold"
  progress:
    spinner: true
    elapsed_time: true
    percentage: true
  components:
    dna:
      icon: "🧬"
      color: "blue"
    immune:
      icon: "🛡️"
      color: "green"
    metabolism:
      icon: "⚡"
      color: "yellow"
    nervous:
      icon: "🧠"
      color: "cyan"
    endocrine:
      icon: "⚖️"
      color: "magenta"
    reproductive:
      icon: "🔄"
      color: "blue"

# Configurazione per modulo
modules:
  dna:
    level: "DEBUG"
    file: "dna.log"
    console: true
    
  immune:
    level: "INFO"
    file: "immune.log"
    console: true
    
  metabolism:
    level: "INFO"
    file: "metabolism.log"
    console: true
    
  nervous:
    level: "DEBUG"
    file: "nervous.log"
    console: true
    
  endocrine:
    level: "INFO"
    file: "endocrine.log"
    console: true
    
  reproductive:
    level: "INFO"
    file: "reproductive.log"
    console: true

# Alert configuration
alerts:
  enabled: true
  levels:
    critical:
      email: true
      telegram: true
    error:
      email: false
      telegram: true
    warning:
      email: false
      telegram: false

# Metriche di logging
metrics:
  enabled: true
  collection_interval: 300  # secondi
  types:
    log_counts:  # Conteggio per livello di log
      enabled: true
      reset_interval: 3600  # Reset contatori ogni ora
    storage:  # Metriche storage
      enabled: true
      check_interval: 900  # Controllo ogni 15 minuti
    errors:  # Metriche errori
      enabled: true
      mttf: true  # Mean Time To Failure
      mttr: true  # Mean Time To Recovery
    performance:  # Performance logging
      enabled: true
      measurements:
        - cpu_usage
        - memory_usage
        - disk_usage
        - log_write_latency
        - rotation_time
